changesetBaseRefs:
  - master
  - origin/master
  - upstream/master

changesetIgnorePatterns:
  - "**/*.test.{js,ts}"
  - "**/*.spec.{js,ts}"

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs
